### ISSUE TITLE
很好的EFI，希望大佬继续维护

### ISSUE THREAD

**Issue by ShangWeizh** [mruru/Xiaomi-12.5#1]
现在macOS12的蓝牙打开设置进行操作，蓝牙有时会无法工作，有时会自行恢复，有时必须要重启macOS。出现此问题前进行蓝牙设置时会卡顿，然后停止工作。只要进行蓝牙设置不会出现以上现象还是能正常使用的

**Comment by mruru** [comment]
蓝牙的问题是通病，可以说是12系统的通病，按照蓝牙驱动开发者的说法，苹果重写了蓝牙堆栈协议造成很多意想不到的问题。

**Comment by ShangWeizh** [comment]
嗯，那使用Big Sur的话就不会出现蓝牙问题吗？如果不会，我就马上回退到11，除非开发者解决这些问题
